#!/usr/bin/python
# -*- coding: UTF-8 _*_

# 运营配置位
test_path_list:
  url_api: '/test_case/test_companyloginOn/'
  url_ui: '/test_flow/test_Authentication/test_login.py/'
#  url_ui: '/test_flow/test_Authentication/test_personalInfoReg.py/'
test_db_list:
  host: '10.10.128.152'
  user: 'root'
  password: 'F&oY6vn$cp#ilsdN'
  port: 3306
  db1: 'chengtay-zero'
  db2: 'chengtay-zcd'
test_redisdb_list:
  host: '10.10.116.15'
  password: 'thctlrbetc'
  port: 6739
  db3: '11'
test_db_sqllist:
    sql0000001: "SET SQL_SAFE_UPDATES = 0;"
    sql0000002: "DELETE FROM `chengtay-zero`.zero_user where userName = {0};"
    sql0000003: "DELETE FROM `chengtay-zero`.zero_user_authentication where phoneNo = {0};"
    sql0000004: "SET SQL_SAFE_UPDATES = 0;"
    sql0000005: "DELETE FROM `chengtay-zcd`.enterprise where enterprise.id = ( select b.enterpriseId FROM `chengtay-zcd`.enterprise_account b where b.phone = {0});"
    sql0000006: "DELETE `chengtay-zcd`.enterprise_account FROM `chengtay-zcd`.enterprise_account WHERE `chengtay-zcd`.enterprise_account.phone = {0};"
test_userlist:
  company_user: '17621198933'
  company_user_pass: 'shuai2019'
test_personalInfoRegList:
  name: '测试用户'
  id_card: '11010119900307475X'