#!/usr/bin/python
# -*- coding: UTF-8 _*_

# 运营配置位
test_path_list:
  url_api: '/test_case/test_companyloginOn/'
  url_ui1: '/test_flow/test_Authentication/test_backStage_authentication.py'
  url_ui2: '/test_flow/test_Tripartite_interaction/'
  url_ui: '/test_flow/test_Authentication/'
  url_ui_forward: 'http://10.10.128.152:10053/user/login'
  url_ui_back: 'http://10.10.128.152:10052/#/account/login'
  url_ui_register: 'http://10.10.128.152:10053/user/register'
  url_ui_forget: 'http://10.10.128.152:10053/user/forget'
test_db_list:
  host: '10.10.128.152'
  user: 'root'
  password: 'F&oY6vn$cp#ilsdN'
  port: 3306
  db1: 'chengtay-zero'
  db2: 'chengtay-zcd'
test_redisdb_list:
  host: '10.10.128.128'
  password: 'ctredis6739'
  port: 6739
  db3: '2'
test_db_sqllist:
    sql0000001: "SET SQL_SAFE_UPDATES = 0;"
    sql0000002: "DELETE FROM `chengtay-zero`.zero_user where userName = {0};"
    sql0000003: "DELETE FROM `chengtay-zero`.zero_user_authentication where phoneNo = {0};"
    sql0000004: "SET SQL_SAFE_UPDATES = 0;"
    sql0000005: "update enterprise set name = 'oldcompanyname' where name in ('潍坊市市政工程设计研究院有限公司','山东艺轩建筑装饰工程有限公司','山东欣立得光电科技有限公司');"
test_personalInfoRegList:
  name: '大佬'
  id_card: '11010119900307475X'
test_backStageUserList:
  company_user: '13816391517'
  company_user_pass: '123456'
  company_bank_pass: '123456'
  company_Guarantee_pass: '123456'
  company_name: '山东欣立得光电科技有限公司'
  autoTest_BankName: 'AutoTest_Bank0016'
  company_bank: '19720000034'
  autoTest_RiskName: 'AutoTest_Risk0016'
  company_Guarantee: '19620000034'
  autoTest_ProductName: 'AutoTest_Product0016'
  product_name: '0001号金融产品'
test_userlist:
  company_user: '17621198985'
  company_user_pass: '123456'